### ISSUE TITLE
Non-ascii characters don't work

### ISSUE THREAD

**Issue by cornop** [rbaron/dict.cc.py#11]
See below.

```
% dict.cc.py en de verfügbar 
Traceback (most recent call last):
  File "/usr/bin/dict.cc.py", line 73, in <module>
    run()
  File "/usr/bin/dict.cc.py", line 54, in run
    args.output_language)
  File "/usr/lib/python3.5/site-packages/dictcc/dictcc.py", line 57, in translate
    response_body = cls._get_response(word, from_language, to_language)
  File "/usr/lib/python3.5/site-packages/dictcc/dictcc.py", line 73, in _get_response
    res = urllib2.urlopen(req).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 983, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 12: ordinal not in range(128)
```

**Comment by rbaron** [comment]
Hi @cornop. Thanks for submitting the issue. You were right, it indeed was broken. Should be fixed now! :+1:

**Comment by cornop** [comment]
Thanks a lot!
